development:
  adapter: async

test:
  adapter: async

production: #2021/9/12変更
  #adapter: redis
  #url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  #channel_prefix: portfolio_production
  adapter: async
