# coding: utf-8

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


categories = Category.create([
  { name: '運動・スポーツ・アウトドア' },
  { name: '文化' },
  { name: '営利団体' },
  { name: '非営利団体・公共団体' },
  { name: 'その他' }
])
subcategories = Subcategory.create!([
  { category_id: '1', name: '野球・ソフトボール' },
  { category_id: '1', name: 'サッカー・フットサル' },
  { category_id: '1', name: 'バスケットボール・3x3' },
  { category_id: '1', name: 'バレーボール' },
  { category_id: '1', name: 'ハンドボール' },
  { category_id: '1', name: 'テニス・ソフトテニス' },
  { category_id: '1', name: '卓球' },
  { category_id: '1', name: 'バドミントン' },
  { category_id: '1', name: 'ゴルフ' },
  { category_id: '1', name: 'ダンス' },
  { category_id: '1', name: 'ヨガ' },
  { category_id: '1', name: '登山・キャンプ' },
  { category_id: '1', name: '釣り・フィッシング' },
  { category_id: '1', name: '水泳' },
  { category_id: '1', name: 'マリンスポーツ' },
  { category_id: '1', name: 'ウィンタースポーツ' },
  { category_id: '1', name: 'スポーツクライミング（ボルダリング・リードなど）' },
  { category_id: '1', name: '陸上競技・マラソン・ジョギング' },
  { category_id: '1', name: '自転車競技・サイクリング' },
  { category_id: '1', name: '体操' },
  { category_id: '1', name: '武道（空手・柔道・剣道など）' },
  { category_id: '1', name: '格闘技' },
  { category_id: '1', name: 'ラグビー' },
  { category_id: '1', name: 'その他スポーツ' },
  { category_id: '2', name: '伝統・文芸・工芸' },
  { category_id: '2', name: '衣食住'},
  { category_id: '2', name: '健康' },
  { category_id: '2', name: '旅行' },
  { category_id: '2', name: '音楽' },
  { category_id: '2', name: '美術・芸術' },
  { category_id: '2', name: '読書' },
  { category_id: '2', name: '教育' },
  { category_id: '2', name: 'コミュニケーション・言語・外国語' },
  { category_id: '2', name: 'テクノロジー・文明' },
  { category_id: '2', name: 'その他' },
  { category_id: '3', name: '株式会社' },
  { category_id: '3', name: 'その他営利団体' },
  { category_id: '4', name: '一般社団・公益社団・公益財団' },
  { category_id: '4', name: 'NPO' },
  { category_id: '4', name: '宗教法人・学校法人' },
  { category_id: '4', name: 'ボランティア団体' },
  { category_id: '4', name: 'その他非営利団体' },
  { category_id: '5', name: 'その他' }
])

prefectures = Prefecture.create!([
  { name: '北海道' },
  { name: '青森県' },
  { name: '岩手県' },
  { name: '宮城県' },
  { name: '秋田県' },
  { name: '山形県' },
  { name: '福島県' },
  { name: '茨城県' },
  { name: '栃木県' },
  { name: '群馬県' },
  { name: '埼玉県' },
  { name: '千葉県' },
  { name: '東京都' },
  { name: '神奈川県' },
  { name: '新潟県' },
  { name: '富山県' },
  { name: '石川県' },
  { name: '福井県' },
  { name: '山梨県' },
  { name: '長野県' },
  { name: '岐阜県' },
  { name: '静岡県' },
  { name: '愛知県' },
  { name: '三重県' },
  { name: '滋賀県' },
  { name: '京都府' },
  { name: '大阪府' },
  { name: '兵庫県' },
  { name: '奈良県' },
  { name: '和歌山県' },
  { name: '鳥取県' },
  { name: '島根県' },
  { name: '岡山県' },
  { name: '広島県' },
  { name: '山口県' },
  { name: '徳島県' },
  { name: '香川県' },
  { name: '愛媛県' },
  { name: '高知県' },
  { name: '福岡県' },
  { name: '佐賀県' },
  { name: '長崎県' },
  { name: '熊本県' },
  { name: '大分県' },
  { name: '宮崎県' },
  { name: '鹿児島県' },
  { name: '沖縄県' },
  { name: '指定なし' }
])

#reaction_emojis = ReactionEmoji.create([
#  { entity_name: '&#x1f500;' },
#  { entity_name: '&#x1f503;' },
#  { entity_name: '&#x1f503;' },
#  { entity_name: '&#x1f501;' },
#  { entity_name: '&#x1f505;' },
#  { entity_name: '&#x1f504;' },
#  { entity_name: '&#x1f923;' },
#  { entity_name: '&#x1f502;' },
#  { entity_name: '&#x1f532;' },
#  { entity_name: '&#x1f509;' },
#  { entity_name: '&#x1f50a;' },
#  { entity_name: '&#x1f507;' },
#  { entity_name: '&#x1f970;' },
#  { entity_name: '&#x1f50d;' },
#  { entity_name: '&#x1f929;' },
#  { entity_name: '&#x1f517;' },
#  { entity_name: '&#x1f517;' },
#  { entity_name: '&#x253a;' }
#])

ReactionImage.create!([
  { emoji_id: '1', entity_name: 'ryokai', images: File.open("public/reaction_images/custom/ryokai.png") },
  { emoji_id: '1', entity_name: 'ryo', images: File.open("public/reaction_images/custom/ryo.png") },
  { emoji_id: '1', entity_name: 'oke', images: File.open("public/reaction_images/custom/oke.png") },
  { emoji_id: '1', entity_name: 'sorena', images: File.open("public/reaction_images/custom/sorena.png") },
  { emoji_id: '1', entity_name: 'shochi_shimashita', images: File.open("public/reaction_images/custom/shochi_shimashita.png") },
  { emoji_id: '1', entity_name: 'kakunin_shimashita', images: File.open("public/reaction_images/custom/kakunin_shimashita.png") },
  { emoji_id: '1', entity_name: 'kakunin_chu', images: File.open("public/reaction_images/custom/kakunin_chu.png") },
  { emoji_id: '1', entity_name: 'kakunin_zumi', images: File.open("public/reaction_images/custom/kakunin_zumi.png") },
  { emoji_id: '1', entity_name: 'shosho_omachikudasai', images: File.open("public/reaction_images/custom/shosho_omachikudasai.png") },
  { emoji_id: '1', entity_name: 'choimachi', images: File.open("public/reaction_images/custom/choimachi.png") },
  { emoji_id: '1', entity_name: 'done', images: File.open("public/reaction_images/custom/done.png") },
  { emoji_id: '1', entity_name: 'iine', images: File.open("public/reaction_images/custom/iine.png") },
  { emoji_id: '1', entity_name: 'yoki', images: File.open("public/reaction_images/custom/yoki....png") },
  { emoji_id: '1', entity_name: 'otsukaresama', images: File.open("public/reaction_images/custom/otsukaresama.png") },
  { emoji_id: '1', entity_name: 'gokurosama', images: File.open("public/reaction_images/custom/gokurosama.png") },
  { emoji_id: '1', entity_name: 'kokiniwa', images: File.open("public/reaction_images/custom/kokiniwa.gif") },
  
  { emoji_id: '2', entity_name: 'nikkori', images: File.open("public/reaction_images/smileys_&_emotion/nikkori.png") },
  { emoji_id: '2', entity_name: 'wai', images: File.open("public/reaction_images/smileys_&_emotion/wai.png") },
  { emoji_id: '2', entity_name: 'egao', images: File.open("public/reaction_images/smileys_&_emotion/egao.png") },
  { emoji_id: '2', entity_name: 'niyatto', images: File.open("public/reaction_images/smileys_&_emotion/niyatto.png") },
  { emoji_id: '2', entity_name: 'kya', images: File.open("public/reaction_images/smileys_&_emotion/kya.png") },
  { emoji_id: '2', entity_name: 'hiyaase_egao', images: File.open("public/reaction_images/smileys_&_emotion/hiyaase_egao.png") },
  { emoji_id: '2', entity_name: 'ureshinaki', images: File.open("public/reaction_images/smileys_&_emotion/ureshinaki.png") },
  { emoji_id: '2', entity_name: 'waraikoroge', images: File.open("public/reaction_images/smileys_&_emotion/waraikoroge.png") },
  { emoji_id: '2', entity_name: 'nikoniko', images: File.open("public/reaction_images/smileys_&_emotion/nikoniko.png") },
  { emoji_id: '2', entity_name: 'tenshinowa', images: File.open("public/reaction_images/smileys_&_emotion/tenshinowa.png") },
  { emoji_id: '2', entity_name: 'hohoemi', images: File.open("public/reaction_images/smileys_&_emotion/hohoemi.png") },
  { emoji_id: '2', entity_name: 'sakasama_no_kao', images: File.open("public/reaction_images/smileys_&_emotion/sakasama_no_kao.png") },
  { emoji_id: '2', entity_name: 'wink', images: File.open("public/reaction_images/smileys_&_emotion/wink.png") },
  { emoji_id: '2', entity_name: 'hottoshita_kao', images: File.open("public/reaction_images/smileys_&_emotion/hottoshita_kao.png") },
  { emoji_id: '2', entity_name: 'mega_heart', images: File.open("public/reaction_images/smileys_&_emotion/mega_heart.png") },
  { emoji_id: '2', entity_name: 'heart_no_egao', images: File.open("public/reaction_images/smileys_&_emotion/heart_no_egao.png") },
  { emoji_id: '2', entity_name: 'nagekiss', images: File.open("public/reaction_images/smileys_&_emotion/nagekiss.png") },
  { emoji_id: '2', entity_name: 'nikkori_kiss', images: File.open("public/reaction_images/smileys_&_emotion/nikkori_kiss.png") },
  { emoji_id: '2', entity_name: 'chu', images: File.open("public/reaction_images/smileys_&_emotion/chu.png") },
  { emoji_id: '2', entity_name: 'nikoniko_perori', images: File.open("public/reaction_images/smileys_&_emotion/nikoniko_perori.png") },
  { emoji_id: '2', entity_name: 'be', images: File.open("public/reaction_images/smileys_&_emotion/be.png") },
  { emoji_id: '2', entity_name: 'mewotojite_be', images: File.open("public/reaction_images/smileys_&_emotion/mewotojite_be.png") },
  { emoji_id: '2', entity_name: 'akkan_be', images: File.open("public/reaction_images/smileys_&_emotion/akkan_be.png") },
  { emoji_id: '2', entity_name: 'huzaketa_kao', images: File.open("public/reaction_images/smileys_&_emotion/huzaketa_kao.png") },
  { emoji_id: '2', entity_name: 'okaneno_kao', images: File.open("public/reaction_images/smileys_&_emotion/okaneno_kao.png") },
  
  { emoji_id: '2', entity_name: 'monocle_wotsuketa_kao', images: File.open("public/reaction_images/smileys_&_emotion/monocle_wotsuketa_kao.png") },
  { emoji_id: '2', entity_name: 'otaku', images: File.open("public/reaction_images/smileys_&_emotion/otaku.png") },
  { emoji_id: '2', entity_name: 'sunglass_de_egao', images: File.open("public/reaction_images/smileys_&_emotion/sunglass_de_egao.png") },
  { emoji_id: '2', entity_name: 'megahoshino_egao', images: File.open("public/reaction_images/smileys_&_emotion/megahoshino_egao.png") },
  { emoji_id: '2', entity_name: 'party_no_kao', images: File.open("public/reaction_images/smileys_&_emotion/party_no_kao.png") },
  { emoji_id: '2', entity_name: 'cowboy', images: File.open("public/reaction_images/smileys_&_emotion/cowboy.png") },
  { emoji_id: '2', entity_name: 'henso', images: File.open("public/reaction_images/smileys_&_emotion/henso.png") },
  
  { emoji_id: '2', entity_name: 'usuwaraino_kao', images: File.open("public/reaction_images/smileys_&_emotion/usuwaraino_kao.png") },
  { emoji_id: '2', entity_name: 'shiraketa_kao', images: File.open("public/reaction_images/smileys_&_emotion/shiraketa_kao.png") },
  { emoji_id: '2', entity_name: 'shitsuboshita_kao', images: File.open("public/reaction_images/smileys_&_emotion/shitsuboshita_kao.png") },
  { emoji_id: '2', entity_name: 'monoomoino_kao', images: File.open("public/reaction_images/smileys_&_emotion/monoomoino_kao.png") },
  { emoji_id: '2', entity_name: 'nayamu_kao', images: File.open("public/reaction_images/smileys_&_emotion/nayamu_kao.png") },
  { emoji_id: '2', entity_name: 'konranshita_kao', images: File.open("public/reaction_images/smileys_&_emotion/konranshita_kao.png") },
  { emoji_id: '2', entity_name: 'sukoshikomatta_kao', images: File.open("public/reaction_images/smileys_&_emotion/sukoshikomatta_kao.png") },
  { emoji_id: '2', entity_name: 'gamanshita_kao', images: File.open("public/reaction_images/smileys_&_emotion/gamanshita_kao.png") },
  { emoji_id: '2', entity_name: 'konwakushita_kao', images: File.open("public/reaction_images/smileys_&_emotion/konwakushita_kao.png") },
  { emoji_id: '2', entity_name: 'tsukareta_kao', images: File.open("public/reaction_images/smileys_&_emotion/tsukareta_kao.png") },
  { emoji_id: '2', entity_name: 'unzarishita_kao', images: File.open("public/reaction_images/smileys_&_emotion/unzarishita_kao.png") },
  { emoji_id: '2', entity_name: 'nakigao', images: File.open("public/reaction_images/smileys_&_emotion/nakigao.png") },
  { emoji_id: '2', entity_name: 'onaki', images: File.open("public/reaction_images/smileys_&_emotion/onaki.png") },
  { emoji_id: '2', entity_name: 'hanaikinoarai_kao', images: File.open("public/reaction_images/smileys_&_emotion/hanaikinoarai_kao.png") },
  { emoji_id: '2', entity_name: 'okotta_kao', images: File.open("public/reaction_images/smileys_&_emotion/okotta_kao.png") },
  { emoji_id: '2', entity_name: 'hukurettsura', images: File.open("public/reaction_images/smileys_&_emotion/hukurettsura.png") },
  { emoji_id: '2', entity_name: 'nonoshitta_kao', images: File.open("public/reaction_images/smileys_&_emotion/nonoshitta_kao.png") },
  { emoji_id: '2', entity_name: 'atamaga_bakuhatsushita_kao', images: File.open("public/reaction_images/smileys_&_emotion/atamaga_bakuhatsushita_kao.png") },
  
  { emoji_id: '2', entity_name: 'atsui_kao', images: File.open("public/reaction_images/smileys_&_emotion/atsui_kao.png") },
  { emoji_id: '2', entity_name: 'samui_kao', images: File.open("public/reaction_images/smileys_&_emotion/samui_kao.png") },
  { emoji_id: '2', entity_name: 'aozameta_kao', images: File.open("public/reaction_images/smileys_&_emotion/aozameta_kao.png") },
  { emoji_id: '2', entity_name: 'aozame_hiyaase', images: File.open("public/reaction_images/smileys_&_emotion/aozame_hiyaase.png") },
  { emoji_id: '2', entity_name: 'kyohu', images: File.open("public/reaction_images/smileys_&_emotion/kyohu.png") },
  { emoji_id: '2', entity_name: 'doshiyo', images: File.open("public/reaction_images/smileys_&_emotion/doshiyo.png") },
  { emoji_id: '2', entity_name: 'hiyaase', images: File.open("public/reaction_images/smileys_&_emotion/hiyaase.png") },
  
  { emoji_id: '2', entity_name: 'hug', images: File.open("public/reaction_images/smileys_&_emotion/hug.png") },
  { emoji_id: '2', entity_name: 'kangaechu', images: File.open("public/reaction_images/smileys_&_emotion/kangaechu.png") },
  { emoji_id: '2', entity_name: 'kuchinitewoateta_kao', images: File.open("public/reaction_images/smileys_&_emotion/kuchinitewoateta_kao.png") },
  { emoji_id: '2', entity_name: 'shi', images: File.open("public/reaction_images/smileys_&_emotion/shi.png") },
  { emoji_id: '2', entity_name: 'kuchichack', images: File.open("public/reaction_images/smileys_&_emotion/kuchichack.png") },
  { emoji_id: '2', entity_name: 'usotsukino_kao', images: File.open("public/reaction_images/smileys_&_emotion/usotsukino_kao.png") },
  
  { emoji_id: '2', entity_name: 'kuchinonai_kao', images: File.open("public/reaction_images/smileys_&_emotion/kuchinonai_kao.png") },
  { emoji_id: '2', entity_name: 'pokerface', images: File.open("public/reaction_images/smileys_&_emotion/pokerface.png") },
  { emoji_id: '2', entity_name: 'muhyojo', images: File.open("public/reaction_images/smileys_&_emotion/muhyojo.png") },
  { emoji_id: '2', entity_name: 'shikametsura', images: File.open("public/reaction_images/smileys_&_emotion/shikametsura.png") },
  { emoji_id: '2', entity_name: 'gyorome', images: File.open("public/reaction_images/smileys_&_emotion/gyorome.png") },
  { emoji_id: '2', entity_name: 'mayuwoageta_kao', images: File.open("public/reaction_images/smileys_&_emotion/mayuwoageta_kao.png") },
  
  { emoji_id: '2', entity_name: 'odoroita_kao', images: File.open("public/reaction_images/smileys_&_emotion/odoroita_kao.png") },
  { emoji_id: '2', entity_name: 'akiregao', images: File.open("public/reaction_images/smileys_&_emotion/akiregao.png") },
  { emoji_id: '2', entity_name: 'kuno', images: File.open("public/reaction_images/smileys_&_emotion/kuno.png") },
  { emoji_id: '2', entity_name: 'kuchigahiraita_kao', images: File.open("public/reaction_images/smileys_&_emotion/kuchigahiraita_kao.png") },
  { emoji_id: '2', entity_name: 'bikkurishita_kao', images: File.open("public/reaction_images/smileys_&_emotion/bikkurishita_kao.png") },
  { emoji_id: '2', entity_name: 'sekimenshita_kao', images: File.open("public/reaction_images/smileys_&_emotion/sekimenshita_kao.png") },
  { emoji_id: '2', entity_name: 'uttaekakeru_kao', images: File.open("public/reaction_images/smileys_&_emotion/uttaekakeru_kao.png") },
  { emoji_id: '2', entity_name: 'nemui_kao', images: File.open("public/reaction_images/smileys_&_emotion/nemui_kao.png") },
  { emoji_id: '2', entity_name: 'neteru_kao', images: File.open("public/reaction_images/smileys_&_emotion/neteru_kao.png") },
  { emoji_id: '2', entity_name: 'yodaregao', images: File.open("public/reaction_images/smileys_&_emotion/yodaregao.png") },
  
  { emoji_id: '2', entity_name: 'bonyarishita_kao', images: File.open("public/reaction_images/smileys_&_emotion/bonyarishita_kao.png") },
  { emoji_id: '2', entity_name: 'memaigao', images: File.open("public/reaction_images/smileys_&_emotion/memaigao.png") },
  { emoji_id: '2', entity_name: 'hakike', images: File.open("public/reaction_images/smileys_&_emotion/hakike.png") },
  { emoji_id: '2', entity_name: 'oto', images: File.open("public/reaction_images/smileys_&_emotion/oto.png") },
  { emoji_id: '2', entity_name: 'kushamigao', images: File.open("public/reaction_images/smileys_&_emotion/kushamigao.png") },
  { emoji_id: '2', entity_name: 'mask_gao', images: File.open("public/reaction_images/smileys_&_emotion/mask_gao.png") },
  { emoji_id: '2', entity_name: 'hatsunetsu', images: File.open("public/reaction_images/smileys_&_emotion/hatsunetsu.png") },
  { emoji_id: '2', entity_name: 'hotaiwomaita_kao', images: File.open("public/reaction_images/smileys_&_emotion/hotaiwomaita_kao.png") },
  
  { emoji_id: '2', entity_name: 'waratta_akuma', images: File.open("public/reaction_images/smileys_&_emotion/waratta_akuma.png") },
  { emoji_id: '2', entity_name: 'okotta_akuma', images: File.open("public/reaction_images/smileys_&_emotion/okotta_akuma.png") },
  { emoji_id: '2', entity_name: 'pierrot', images: File.open("public/reaction_images/smileys_&_emotion/pierrot.png") },
  { emoji_id: '2', entity_name: 'obake', images: File.open("public/reaction_images/smileys_&_emotion/obake.png") },
  { emoji_id: '2', entity_name: 'dokuro', images: File.open("public/reaction_images/smileys_&_emotion/dokuro.png") },
  { emoji_id: '2', entity_name: 'alien', images: File.open("public/reaction_images/smileys_&_emotion/alien.png") },
  
  { emoji_id: '2', entity_name: 'two_hearts', images: File.open("public/reaction_images/smileys_&_emotion/two_hearts.png") },
  { emoji_id: '2', entity_name: 'growing_heart', images: File.open("public/reaction_images/smileys_&_emotion/growing_heart.png") },
  { emoji_id: '2', entity_name: 'heart_with_arrow', images: File.open("public/reaction_images/smileys_&_emotion/heart_with_arrow.png") },
  { emoji_id: '2', entity_name: 'broken_heart', images: File.open("public/reaction_images/smileys_&_emotion/broken_heart.png") },
  
  { emoji_id: '2', entity_name: '100tenmanten', images: File.open("public/reaction_images/smileys_&_emotion/100tenmanten.png") },
  { emoji_id: '2', entity_name: 'taihen_yokudekimashita', images: File.open("public/reaction_images/smileys_&_emotion/taihen_yokudekimashita.png") },
  { emoji_id: '2', entity_name: 'sparkles', images: File.open("public/reaction_images/smileys_&_emotion/sparkles.png") },
  { emoji_id: '2', entity_name: 'sweat_droplets', images: File.open("public/reaction_images/smileys_&_emotion/sweat_droplets.png") },
  { emoji_id: '2', entity_name: 'ikari_mark', images: File.open("public/reaction_images/smileys_&_emotion/ikari_mark.png") },
  { emoji_id: '2', entity_name: 'zzz', images: File.open("public/reaction_images/smileys_&_emotion/zzz.png") },
  
  
  { emoji_id: '3', entity_name: 'palms_up_together', images: File.open("public/reaction_images/body_&_gesture_&_person/palms_up_together.png") },
  { emoji_id: '3', entity_name: 'open_hands', images: File.open("public/reaction_images/body_&_gesture_&_person/open_hands.png") },
  { emoji_id: '3', entity_name: 'banzai', images: File.open("public/reaction_images/body_&_gesture_&_person/banzai.png") },
  { emoji_id: '3', entity_name: 'clapping_hands', images: File.open("public/reaction_images/body_&_gesture_&_person/clapping_hands.png") },
  { emoji_id: '3', entity_name: 'handshake', images: File.open("public/reaction_images/body_&_gesture_&_person/handshake.png") },
  { emoji_id: '3', entity_name: 'thumbs_up', images: File.open("public/reaction_images/body_&_gesture_&_person/thumbs_up.png") },
  { emoji_id: '3', entity_name: 'thumbs_down', images: File.open("public/reaction_images/body_&_gesture_&_person/thumbs_down.png") },
  { emoji_id: '3', entity_name: 'gu', images: File.open("public/reaction_images/body_&_gesture_&_person/gu.png") },
  { emoji_id: '3', entity_name: 'genkotsu', images: File.open("public/reaction_images/body_&_gesture_&_person/genkotsu.png") },
  { emoji_id: '3', entity_name: 'hidarimuki_no_kobushi', images: File.open("public/reaction_images/body_&_gesture_&_person/hidarimuki_no_kobushi.png") },
  { emoji_id: '3', entity_name: 'migimuki_no_kobushi', images: File.open("public/reaction_images/body_&_gesture_&_person/migimuki_no_kobushi.png") },
  { emoji_id: '3', entity_name: 'crossed_fingers', images: File.open("public/reaction_images/body_&_gesture_&_person/crossed_fingers.png") },
  { emoji_id: '3', entity_name: 'v_sign', images: File.open("public/reaction_images/body_&_gesture_&_person/v_sign.png") },
  { emoji_id: '3', entity_name: 'love_you_gesture', images: File.open("public/reaction_images/body_&_gesture_&_person/love_you_gesture.png") },
  { emoji_id: '3', entity_name: 'metal_pose', images: File.open("public/reaction_images/body_&_gesture_&_person/metal_pose.png") },
  { emoji_id: '3', entity_name: 'ok_sign', images: File.open("public/reaction_images/body_&_gesture_&_person/ok_sign.png") },
  { emoji_id: '3', entity_name: 'raised_hand', images: File.open("public/reaction_images/body_&_gesture_&_person/raised_hand.png") },
  { emoji_id: '3', entity_name: 'hiraita_te', images: File.open("public/reaction_images/body_&_gesture_&_person/hiraita_te.png") },
  { emoji_id: '3', entity_name: 'spock_hand', images: File.open("public/reaction_images/body_&_gesture_&_person/spock_hand.png") },
  { emoji_id: '3', entity_name: 'waving_hand', images: File.open("public/reaction_images/body_&_gesture_&_person/waving_hand.png") },
  { emoji_id: '3', entity_name: 'call_me_hand', images: File.open("public/reaction_images/body_&_gesture_&_person/call_me_hand.png") },
  { emoji_id: '3', entity_name: 'chikarakobu', images: File.open("public/reaction_images/body_&_gesture_&_person/chikarakobu.png") },
  { emoji_id: '3', entity_name: 'writing_hand', images: File.open("public/reaction_images/body_&_gesture_&_person/writing_hand.png") },
  { emoji_id: '3', entity_name: 'folded_hands', images: File.open("public/reaction_images/body_&_gesture_&_person/folded_hands.png") },
  { emoji_id: '3', entity_name: 'ashiato', images: File.open("public/reaction_images/body_&_gesture_&_person/ashiato.png") },
  { emoji_id: '3', entity_name: 'katame', images: File.open("public/reaction_images/body_&_gesture_&_person/katame.png") },
  { emoji_id: '3', entity_name: 'ryome', images: File.open("public/reaction_images/body_&_gesture_&_person/ryome.png") },
  
  { emoji_id: '3', entity_name: 'ojigi_man', images: File.open("public/reaction_images/body_&_gesture_&_person/ojigi_man.png") },
  { emoji_id: '3', entity_name: 'ojigi_woman', images: File.open("public/reaction_images/body_&_gesture_&_person/ojigi_woman.png") },
  { emoji_id: '3', entity_name: 'goannai_man', images: File.open("public/reaction_images/body_&_gesture_&_person/goannai_man.png") },
  { emoji_id: '3', entity_name: 'goannai_woman', images: File.open("public/reaction_images/body_&_gesture_&_person/goannai_woman.png") },
  { emoji_id: '3', entity_name: 'ok_pose_man', images: File.open("public/reaction_images/body_&_gesture_&_person/ok_pose_man.png") },
  { emoji_id: '3', entity_name: 'ok_pose_woman', images: File.open("public/reaction_images/body_&_gesture_&_person/ok_pose_woman.png") },
  { emoji_id: '3', entity_name: 'no_pose_man', images: File.open("public/reaction_images/body_&_gesture_&_person/no_pose_man.png") },
  { emoji_id: '3', entity_name: 'no_pose_woman', images: File.open("public/reaction_images/body_&_gesture_&_person/no_pose_woman.png") },
  { emoji_id: '3', entity_name: 'kyoshu_man', images: File.open("public/reaction_images/body_&_gesture_&_person/kyoshu_man.png") },
  { emoji_id: '3', entity_name: 'kyoshu_woman', images: File.open("public/reaction_images/body_&_gesture_&_person/kyoshu_woman.png") },
  { emoji_id: '3', entity_name: 'facepalming_man', images: File.open("public/reaction_images/body_&_gesture_&_person/facepalming_man.png") },
  { emoji_id: '3', entity_name: 'facepalming_woman', images: File.open("public/reaction_images/body_&_gesture_&_person/facepalming_woman.png") },
  { emoji_id: '3', entity_name: 'shrugging_man', images: File.open("public/reaction_images/body_&_gesture_&_person/shrugging_man.png") },
  { emoji_id: '3', entity_name: 'shrugging_woman', images: File.open("public/reaction_images/body_&_gesture_&_person/shrugging_woman.png") },
  { emoji_id: '3', entity_name: 'frowning_man', images: File.open("public/reaction_images/body_&_gesture_&_person/frowning_man.png") },
  { emoji_id: '3', entity_name: 'frowning_woman', images: File.open("public/reaction_images/body_&_gesture_&_person/frowning_woman.png") },
  { emoji_id: '3', entity_name: 'pouting_man', images: File.open("public/reaction_images/body_&_gesture_&_person/pouting_man.png") },
  { emoji_id: '3', entity_name: 'pouting_woman', images: File.open("public/reaction_images/body_&_gesture_&_person/pouting_woman.png") },
  { emoji_id: '3', entity_name: 'goannai_man', images: File.open("public/reaction_images/body_&_gesture_&_person/goannai_man.png") },
  { emoji_id: '3', entity_name: 'goannai_woman', images: File.open("public/reaction_images/body_&_gesture_&_person/goannai_woman.png") },
  { emoji_id: '3', entity_name: 'walking_man', images: File.open("public/reaction_images/body_&_gesture_&_person/walking_man.png") },
  { emoji_id: '3', entity_name: 'walking_woman', images: File.open("public/reaction_images/body_&_gesture_&_person/walking_woman.png") },
  { emoji_id: '3', entity_name: 'running_man', images: File.open("public/reaction_images/body_&_gesture_&_person/running_man.png") },
  { emoji_id: '3', entity_name: 'running_woman', images: File.open("public/reaction_images/body_&_gesture_&_person/running_woman.png") },
  { emoji_id: '3', entity_name: 'dancing_man', images: File.open("public/reaction_images/body_&_gesture_&_person/dancing_man.png") },
  { emoji_id: '3', entity_name: 'dancing_woman', images: File.open("public/reaction_images/body_&_gesture_&_person/dancing_woman.png") },
  { emoji_id: '3', entity_name: 'man_in_lotus_position', images: File.open("public/reaction_images/body_&_gesture_&_person/man_in_lotus_position.png") },
  { emoji_id: '3', entity_name: 'woman_in_lotus_position', images: File.open("public/reaction_images/body_&_gesture_&_person/woman_in_lotus_position.png") },
  { emoji_id: '3', entity_name: 'person_taking_bath', images: File.open("public/reaction_images/body_&_gesture_&_person/person_taking_bath.png") },
  { emoji_id: '3', entity_name: 'person_in_bed', images: File.open("public/reaction_images/body_&_gesture_&_person/person_in_bed.png") },
  
  { emoji_id: '4', entity_name: 'sun_with_face', images: File.open("public/reaction_images/nature_&_place/sun_with_face.png") },
  { emoji_id: '4', entity_name: 'full_moon_with_face', images: File.open("public/reaction_images/nature_&_place/full_moon_with_face.png") },
  { emoji_id: '4', entity_name: 'full_moon', images: File.open("public/reaction_images/nature_&_place/full_moon.png") },
  { emoji_id: '4', entity_name: 'crescent_moon', images: File.open("public/reaction_images/nature_&_place/crescent_moon.png") },
  { emoji_id: '4', entity_name: 'ringed_planet', images: File.open("public/reaction_images/nature_&_place/ringed_planet.png") },
  { emoji_id: '4', entity_name: 'star', images: File.open("public/reaction_images/nature_&_place/star.png") },
  { emoji_id: '4', entity_name: 'glowing_star', images: File.open("public/reaction_images/nature_&_place/glowing_star.png") },
  { emoji_id: '4', entity_name: 'shooting_star', images: File.open("public/reaction_images/nature_&_place/shooting_star.png") },
  { emoji_id: '4', entity_name: 'milky_way', images: File.open("public/reaction_images/nature_&_place/milky_way.png") },
  { emoji_id: '4', entity_name: 'hare_tokidoki_kumori', images: File.open("public/reaction_images/nature_&_place/hare_tokidoki_kumori.png") },
  { emoji_id: '4', entity_name: 'kumori_tokidoki_hare', images: File.open("public/reaction_images/nature_&_place/kumori_tokidoki_hare.png") },
  { emoji_id: '4', entity_name: 'ame_tokidoki_hare', images: File.open("public/reaction_images/nature_&_place/ame_tokidoki_hare.png") },
  { emoji_id: '4', entity_name: 'cloud_with_rain', images: File.open("public/reaction_images/nature_&_place/cloud_with_rain.png") },
  { emoji_id: '4', entity_name: 'cloud_with_lightning_and_rain', images: File.open("public/reaction_images/nature_&_place/cloud_with_lightning_and_rain.png") },
  { emoji_id: '4', entity_name: 'cloud_with_lightning', images: File.open("public/reaction_images/nature_&_place/cloud_with_lightning.png") },
  { emoji_id: '4', entity_name: 'cloud_with_snow', images: File.open("public/reaction_images/nature_&_place/cloud_with_snow.png") },
  { emoji_id: '4', entity_name: 'snowman', images: File.open("public/reaction_images/nature_&_place/snowman.png") },
  { emoji_id: '4', entity_name: 'umbrella_with_rain', images: File.open("public/reaction_images/nature_&_place/umbrella_with_rain.png") },
  { emoji_id: '4', entity_name: 'tornado', images: File.open("public/reaction_images/nature_&_place/tornado.png") },
  { emoji_id: '4', entity_name: 'wave', images: File.open("public/reaction_images/nature_&_place/wave.png") },
  { emoji_id: '4', entity_name: 'fog', images: File.open("public/reaction_images/nature_&_place/fog.png") },
  { emoji_id: '4', entity_name: 'rainbow', images: File.open("public/reaction_images/nature_&_place/rainbow.png") },
  { emoji_id: '4', entity_name: 'high_voltage', images: File.open("public/reaction_images/nature_&_place/high_voltage.png") },
  { emoji_id: '4', entity_name: 'collision', images: File.open("public/reaction_images/nature_&_place/collision.png") },
  { emoji_id: '4', entity_name: 'fire', images: File.open("public/reaction_images/nature_&_place/fire.png") },
  { emoji_id: '4', entity_name: 'dashing_away', images: File.open("public/reaction_images/nature_&_place/dashing_away.png") },
  { emoji_id: '4', entity_name: 'droplet', images: File.open("public/reaction_images/nature_&_place/droplet.png") },
  
  { emoji_id: '4', entity_name: 'seedling', images: File.open("public/reaction_images/nature_&_place/seedling.png") },
  { emoji_id: '4', entity_name: 'sheaf_of_rice', images: File.open("public/reaction_images/nature_&_place/sheaf_of_rice.png") },
  { emoji_id: '4', entity_name: 'four_leaf_clover', images: File.open("public/reaction_images/nature_&_place/four_leaf_clover.png") },
  { emoji_id: '4', entity_name: 'leaf_fluttering_in_wind', images: File.open("public/reaction_images/nature_&_place/leaf_fluttering_in_wind.png") },
  { emoji_id: '4', entity_name: 'fallen_leaf', images: File.open("public/reaction_images/nature_&_place/fallen_leaf.png") },
  { emoji_id: '4', entity_name: 'maple_leaf', images: File.open("public/reaction_images/nature_&_place/maple_leaf.png") },
  { emoji_id: '4', entity_name: 'bouquet', images: File.open("public/reaction_images/nature_&_place/bouquet.png") },
  { emoji_id: '4', entity_name: 'rosette', images: File.open("public/reaction_images/nature_&_place/rosette.png") },
  { emoji_id: '4', entity_name: 'tulip', images: File.open("public/reaction_images/nature_&_place/tulip.png") },
  { emoji_id: '4', entity_name: 'rose', images: File.open("public/reaction_images/nature_&_place/rose.png") },
  { emoji_id: '4', entity_name: 'wilted_flower', images: File.open("public/reaction_images/nature_&_place/wilted_flower.png") },
  { emoji_id: '4', entity_name: 'cherry_blossom', images: File.open("public/reaction_images/nature_&_place/cherry_blossom.png") },
  { emoji_id: '4', entity_name: 'hibiscus', images: File.open("public/reaction_images/nature_&_place/hibiscus.png") },
  { emoji_id: '4', entity_name: 'sunflower', images: File.open("public/reaction_images/nature_&_place/sunflower.png") },
  { emoji_id: '4', entity_name: 'blossom', images: File.open("public/reaction_images/nature_&_place/blossom.png") },
  
  { emoji_id: '4', entity_name: 'railway_track', images: File.open("public/reaction_images/nature_&_place/railway_track.png") },
  { emoji_id: '4', entity_name: 'motorway', images: File.open("public/reaction_images/nature_&_place/motorway.png") },
  { emoji_id: '4', entity_name: 'sunrise', images: File.open("public/reaction_images/nature_&_place/sunrise.png") },
  { emoji_id: '4', entity_name: 'sunrise_over_mountains', images: File.open("public/reaction_images/nature_&_place/sunrise_over_mountains.png") },
  { emoji_id: '4', entity_name: 'sunset', images: File.open("public/reaction_images/nature_&_place/sunset.png") },
  { emoji_id: '4', entity_name: 'cityscape_at_dusk', images: File.open("public/reaction_images/nature_&_place/cityscape_at_dusk.png") },
  { emoji_id: '4', entity_name: 'cityscape', images: File.open("public/reaction_images/nature_&_place/cityscape.png") },
  { emoji_id: '4', entity_name: 'night_with_stars', images: File.open("public/reaction_images/nature_&_place/night_with_stars.png") },
  { emoji_id: '4', entity_name: 'bridge_at_night', images: File.open("public/reaction_images/nature_&_place/bridge_at_night.png") },
  { emoji_id: '4', entity_name: 'foggy', images: File.open("public/reaction_images/nature_&_place/foggy.png") },
  { emoji_id: '4', entity_name: 'beach_with_umbrella', images: File.open("public/reaction_images/nature_&_place/beach_with_umbrella.png") },
  { emoji_id: '4', entity_name: 'desert_island', images: File.open("public/reaction_images/nature_&_place/desert_island.png") },
  { emoji_id: '4', entity_name: 'desert', images: File.open("public/reaction_images/nature_&_place/desert.png") },
  { emoji_id: '4', entity_name: 'national_park', images: File.open("public/reaction_images/nature_&_place/national_park.png") },
  
  { emoji_id: '4', entity_name: 'moai', images: File.open("public/reaction_images/nature_&_place/moai.png") },
  { emoji_id: '4', entity_name: 'statue_of_liberty', images: File.open("public/reaction_images/nature_&_place/statue_of_liberty.png") },
  { emoji_id: '4', entity_name: 'tokyo_tower', images: File.open("public/reaction_images/nature_&_place/tokyo_tower.png") },
  
  { emoji_id: '5', entity_name: 'kadomatsu', images: File.open("public/reaction_images/activity_&_tradition_&_features/kadomatsu.png") },
  { emoji_id: '5', entity_name: 'red_envelope', images: File.open("public/reaction_images/activity_&_tradition_&_features/red_envelope.png") },
  { emoji_id: '5', entity_name: 'hinamatsuri', images: File.open("public/reaction_images/activity_&_tradition_&_features/hinamatsuri.png") },
  { emoji_id: '5', entity_name: 'koinobori', images: File.open("public/reaction_images/activity_&_tradition_&_features/koinobori.png") },
  { emoji_id: '5', entity_name: 'tanabata_tree', images: File.open("public/reaction_images/activity_&_tradition_&_features/tanabata_tree.png") },
  { emoji_id: '5', entity_name: 'hurin', images: File.open("public/reaction_images/activity_&_tradition_&_features/hurin.png") },
  { emoji_id: '5', entity_name: 'fireworks', images: File.open("public/reaction_images/activity_&_tradition_&_features/fireworks.png") },
  { emoji_id: '5', entity_name: 'sparkler', images: File.open("public/reaction_images/activity_&_tradition_&_features/sparkler.png") },
  { emoji_id: '5', entity_name: 'otsukimi', images: File.open("public/reaction_images/activity_&_tradition_&_features/otsukimi.png") },
  { emoji_id: '5', entity_name: 'jack_o_lantern', images: File.open("public/reaction_images/activity_&_tradition_&_features/jack_o_lantern.png") },
  { emoji_id: '5', entity_name: 'christmas_tree', images: File.open("public/reaction_images/activity_&_tradition_&_features/christmas_tree.png") },
  { emoji_id: '5', entity_name: 'wrapped_gift', images: File.open("public/reaction_images/activity_&_tradition_&_features/wrapped_gift.png") },
  { emoji_id: '5', entity_name: 'party_popper', images: File.open("public/reaction_images/activity_&_tradition_&_features/party_popper.png") },
  { emoji_id: '5', entity_name: 'confetti_ball', images: File.open("public/reaction_images/activity_&_tradition_&_features/confetti_ball.png") },
  { emoji_id: '5', entity_name: 'hot_beverage', images: File.open("public/reaction_images/activity_&_tradition_&_features/hot_beverage.png") },
  { emoji_id: '5', entity_name: 'yunomi', images: File.open("public/reaction_images/activity_&_tradition_&_features/yunomi.png") },
  { emoji_id: '5', entity_name: 'beer_mug', images: File.open("public/reaction_images/activity_&_tradition_&_features/beer_mug.png") },
  { emoji_id: '5', entity_name: 'clinking_beer_mugs', images: File.open("public/reaction_images/activity_&_tradition_&_features/clinking_beer_mugs.png") },
  { emoji_id: '5', entity_name: 'clinking_glasses', images: File.open("public/reaction_images/activity_&_tradition_&_features/clinking_glasses.png") },
  { emoji_id: '5', entity_name: 'wine_glass', images: File.open("public/reaction_images/activity_&_tradition_&_features/wine_glass.png") },
  { emoji_id: '5', entity_name: 'cocktail_glass', images: File.open("public/reaction_images/activity_&_tradition_&_features/cocktail_glass.png") },
  { emoji_id: '5', entity_name: 'champagne', images: File.open("public/reaction_images/activity_&_tradition_&_features/champagne.png") },
  { emoji_id: '5', entity_name: 'tokkuri', images: File.open("public/reaction_images/activity_&_tradition_&_features/tokkuri.png") },
  { emoji_id: '5', entity_name: 'joker', images: File.open("public/reaction_images/activity_&_tradition_&_features/joker.png") },
  { emoji_id: '5', entity_name: 'mahjong_red_dragon', images: File.open("public/reaction_images/activity_&_tradition_&_features/mahjong_red_dragon.png") },
  { emoji_id: '5', entity_name: 'hanahuda', images: File.open("public/reaction_images/activity_&_tradition_&_features/hanahuda.png") },
  
  { emoji_id: '6', entity_name: 'loudspeaker', images: File.open("public/reaction_images/objects_&_others/loudspeaker.png") },
  { emoji_id: '6', entity_name: 'megaphone', images: File.open("public/reaction_images/objects_&_others/megaphone.png") },
  { emoji_id: '6', entity_name: 'bell', images: File.open("public/reaction_images/objects_&_others/bell.png") },
  { emoji_id: '6', entity_name: 'bell_with_slash', images: File.open("public/reaction_images/objects_&_others/bell_with_slash.png") },
  { emoji_id: '6', entity_name: 'musical_notes', images: File.open("public/reaction_images/objects_&_others/musical_notes.png") },
  { emoji_id: '6', entity_name: 'microphone', images: File.open("public/reaction_images/objects_&_others/microphone.png") },
  { emoji_id: '6', entity_name: 'studio_microphone', images: File.open("public/reaction_images/objects_&_others/studio_microphone.png") },
  { emoji_id: '6', entity_name: 'light_bulb', images: File.open("public/reaction_images/objects_&_others/light_bulb.png") },
  { emoji_id: '6', entity_name: 'candle', images: File.open("public/reaction_images/objects_&_others/candle.png") },
  { emoji_id: '6', entity_name: 'red_paper_lantern', images: File.open("public/reaction_images/objects_&_others/red_paper_lantern.png") },
  
  { emoji_id: '6', entity_name: 'dollar_banknote', images: File.open("public/reaction_images/objects_&_others/dollar_banknote.png") },
  { emoji_id: '6', entity_name: 'euro_banknote', images: File.open("public/reaction_images/objects_&_others/euro_banknote.png") },
  { emoji_id: '6', entity_name: 'pound_banknote', images: File.open("public/reaction_images/objects_&_others/pound_banknote.png") },
  { emoji_id: '6', entity_name: 'yen_banknote', images: File.open("public/reaction_images/objects_&_others/yen_banknote.png") },
  { emoji_id: '6', entity_name: 'money_with_wings', images: File.open("public/reaction_images/objects_&_others/money_with_wings.png") },
  { emoji_id: '6', entity_name: 'money_bag', images: File.open("public/reaction_images/objects_&_others/money_bag.png") },
  
  { emoji_id: '6', entity_name: 'magnifying_glass', images: File.open("public/reaction_images/objects_&_others/magnifying_glass.png") },
  { emoji_id: '6', entity_name: 'memo', images: File.open("public/reaction_images/objects_&_others/memo.png") },
  { emoji_id: '6', entity_name: 'hourglass_not_done', images: File.open("public/reaction_images/objects_&_others/hourglass_not_done.png") },
  
  { emoji_id: '6', entity_name: 'roller_coaster', images: File.open("public/reaction_images/objects_&_others/roller_coaster.png") },
  { emoji_id: '6', entity_name: 'carousel_horse', images: File.open("public/reaction_images/objects_&_others/carousel_horse.png") },
  { emoji_id: '6', entity_name: 'parachute', images: File.open("public/reaction_images/objects_&_others/parachute.png") },
  { emoji_id: '6', entity_name: 'water_pistol', images: File.open("public/reaction_images/objects_&_others/water_pistol.png") },
  { emoji_id: '6', entity_name: 'teddy_bear', images: File.open("public/reaction_images/objects_&_others/teddy_bear.png") },
  { emoji_id: '6', entity_name: 'shopping_cart', images: File.open("public/reaction_images/objects_&_others/shopping_cart.png") },
  { emoji_id: '6', entity_name: 'construction', images: File.open("public/reaction_images/objects_&_others/construction.png") },
  
  { emoji_id: '7', entity_name: 'check_mark', images: File.open("public/reaction_images/symbols/check_mark.png") },
  { emoji_id: '7', entity_name: 'heavy_large_circle', images: File.open("public/reaction_images/symbols/heavy_large_circle.png") },
  { emoji_id: '7', entity_name: 'cross_mark', images: File.open("public/reaction_images/symbols/cross_mark.png") },
  { emoji_id: '7', entity_name: 'exclamation_mark', images: File.open("public/reaction_images/symbols/exclamation_mark.png") },
  { emoji_id: '7', entity_name: 'maruka_button', images: File.open("public/reaction_images/symbols/maruka_button.png") },
  { emoji_id: '7', entity_name: 'marutoku_button', images: File.open("public/reaction_images/symbols/marutoku_button.png") },
  { emoji_id: '7', entity_name: 'ok_button', images: File.open("public/reaction_images/symbols/ok_button.png") },
  { emoji_id: '7', entity_name: 'ng_button', images: File.open("public/reaction_images/symbols/ng_button.png") },
  { emoji_id: '7', entity_name: 'beginners_mark', images: File.open("public/reaction_images/symbols/beginners_mark.png") }
])

User.create!(id: '0', family_name: 'celeste', first_name: 'bot', accountName: 'celestebot', email: 'celethread136@gmail.com', password: 'dummy_pass')

Community.create!(id: 'celestebot', user_id: '0', communityName: 'celeste_bot', category_id: '5', subcategory_id: '5', prefecture_id: '13', images: File.open("./app/assets/images/icons/image_default.png"), public: '0')

CommunityParticipant.create!(id: '0', user_id: '0', community_id: 'celestebot', role: '1')

Channel.create!(id: 'celestebot', user_id: '0', community_id: 'celestebot', channelName: 'celeste_channel_bot', color: '#a2efef', public: '2')

Gthread.create!(id: 'celestebot', user_id: '0', community_id: 'celestebot', channel_id: 'celestebot', title: 'celeste_botです！', description: '<p>' + 'こんにちは、celeste_botです！' + '</p>')
